apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-example
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: fastapi-example
          image: your-docker-registry/fastapi-example:prod
          env:
            - name: ENV
              value: "prod"
