apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:pmpaulino/homelab.git'
    targetRevision: main
    path: 'infra/tailscale/crds'
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
