apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:pmpaulino/homelab.git'
    targetRevision: main
    path: 'infra/argocd/overlays/nonprod'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5  # number of retries
      backoff:
        duration: 5s # initial backoff duration
        factor: 2    # multiplication factor for subsequent retries
        maxDuration: 3m # maximum backoff duration
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # Can help with race conditions
