apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  project: default
  source:
    repoURL: 'git@github.com:pmpaulino/sealed-secrets.git'
    targetRevision: main
    path: 'overlays/nonprod'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
