apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: 'git@github.com:pmpaulino/homelab-argo-apps.git'
    targetRevision: main
    path: environments
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
