apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: home-assistant
          image: your-docker-registry/home-assistant:nonprod
          env:
            - name: ENV
              value: "nonprod"
