---
# Source: kube-prometheus-stack/charts/grafana/templates/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    helm.sh/chart: grafana-8.9.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/version: 11.5.1
  name: kube-prometheus-stack-grafana-clusterrole
rules:
  - apiGroups:
      - ""
    resources: # "" indicates the core API group
      - configmaps
      - secrets
    verbs:
      - get
      - watch
      - list
