apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- alertmanager_kube-prometheus-stack-alertmanager.yaml
- clusterrole_kube-prometheus-stack-admission.yaml
- clusterrole_kube-prometheus-stack-grafana-clusterrole.yaml
- clusterrole_kube-prometheus-stack-kube-state-metrics.yaml
- clusterrole_kube-prometheus-stack-operator.yaml
- clusterrole_kube-prometheus-stack-prometheus.yaml
- clusterrolebinding_kube-prometheus-stack-admission.yaml
- clusterrolebinding_kube-prometheus-stack-grafana-clusterrolebinding.yaml
- clusterrolebinding_kube-prometheus-stack-kube-state-metrics.yaml
- clusterrolebinding_kube-prometheus-stack-operator.yaml
- clusterrolebinding_kube-prometheus-stack-prometheus.yaml
- configmap_kube-prometheus-stack-alertmanager-overview.yaml
- configmap_kube-prometheus-stack-apiserver.yaml
- configmap_kube-prometheus-stack-cluster-total.yaml
- configmap_kube-prometheus-stack-controller-manager.yaml
- configmap_kube-prometheus-stack-etcd.yaml
- configmap_kube-prometheus-stack-grafana-config-dashboards.yaml
- configmap_kube-prometheus-stack-grafana-datasource.yaml
- configmap_kube-prometheus-stack-grafana-overview.yaml
- configmap_kube-prometheus-stack-grafana-test.yaml
- configmap_kube-prometheus-stack-grafana.yaml
- configmap_kube-prometheus-stack-k8s-coredns.yaml
- configmap_kube-prometheus-stack-k8s-resources-cluster.yaml
- configmap_kube-prometheus-stack-k8s-resources-multicluster.yaml
- configmap_kube-prometheus-stack-k8s-resources-namespace.yaml
- configmap_kube-prometheus-stack-k8s-resources-node.yaml
- configmap_kube-prometheus-stack-k8s-resources-pod.yaml
- configmap_kube-prometheus-stack-k8s-resources-workload.yaml
- configmap_kube-prometheus-stack-k8s-resources-workloads-namespace.yaml
- configmap_kube-prometheus-stack-kubelet.yaml
- configmap_kube-prometheus-stack-namespace-by-pod.yaml
- configmap_kube-prometheus-stack-namespace-by-workload.yaml
- configmap_kube-prometheus-stack-node-cluster-rsrc-use.yaml
- configmap_kube-prometheus-stack-node-rsrc-use.yaml
- configmap_kube-prometheus-stack-nodes-aix.yaml
- configmap_kube-prometheus-stack-nodes-darwin.yaml
- configmap_kube-prometheus-stack-nodes.yaml
- configmap_kube-prometheus-stack-persistentvolumesusage.yaml
- configmap_kube-prometheus-stack-pod-total.yaml
- configmap_kube-prometheus-stack-prometheus.yaml
- configmap_kube-prometheus-stack-proxy.yaml
- configmap_kube-prometheus-stack-scheduler.yaml
- configmap_kube-prometheus-stack-workload-total.yaml
- daemonset_kube-prometheus-stack-prometheus-node-exporter.yaml
- deployment_kube-prometheus-stack-grafana.yaml
- deployment_kube-prometheus-stack-kube-state-metrics.yaml
- deployment_kube-prometheus-stack-operator.yaml
- job_kube-prometheus-stack-admission-create.yaml
- job_kube-prometheus-stack-admission-patch.yaml
- mutatingwebhookconfiguration_kube-prometheus-stack-admission.yaml
- pod_kube-prometheus-stack-grafana-test.yaml
- prometheus_kube-prometheus-stack-prometheus.yaml
- prometheusrule_kube-prometheus-stack-alertmanager.rules.yaml
- prometheusrule_kube-prometheus-stack-config-reloaders.yaml
- prometheusrule_kube-prometheus-stack-etcd.yaml
- prometheusrule_kube-prometheus-stack-general.rules.yaml
- prometheusrule_kube-prometheus-stack-k8s.rules.container-cpu-usage-seconds-tot.yaml
- prometheusrule_kube-prometheus-stack-k8s.rules.container-memory-cache.yaml
- prometheusrule_kube-prometheus-stack-k8s.rules.container-memory-rss.yaml
- prometheusrule_kube-prometheus-stack-k8s.rules.container-memory-swap.yaml
- prometheusrule_kube-prometheus-stack-k8s.rules.container-memory-working-set-by.yaml
- prometheusrule_kube-prometheus-stack-k8s.rules.container-resource.yaml
- prometheusrule_kube-prometheus-stack-k8s.rules.pod-owner.yaml
- prometheusrule_kube-prometheus-stack-kube-apiserver-availability.rules.yaml
- prometheusrule_kube-prometheus-stack-kube-apiserver-burnrate.rules.yaml
- prometheusrule_kube-prometheus-stack-kube-apiserver-histogram.rules.yaml
- prometheusrule_kube-prometheus-stack-kube-apiserver-slos.yaml
- prometheusrule_kube-prometheus-stack-kube-prometheus-general.rules.yaml
- prometheusrule_kube-prometheus-stack-kube-prometheus-node-recording.rules.yaml
- prometheusrule_kube-prometheus-stack-kube-scheduler.rules.yaml
- prometheusrule_kube-prometheus-stack-kube-state-metrics.yaml
- prometheusrule_kube-prometheus-stack-kubelet.rules.yaml
- prometheusrule_kube-prometheus-stack-kubernetes-apps.yaml
- prometheusrule_kube-prometheus-stack-kubernetes-resources.yaml
- prometheusrule_kube-prometheus-stack-kubernetes-storage.yaml
- prometheusrule_kube-prometheus-stack-kubernetes-system-apiserver.yaml
- prometheusrule_kube-prometheus-stack-kubernetes-system-controller-manager.yaml
- prometheusrule_kube-prometheus-stack-kubernetes-system-kube-proxy.yaml
- prometheusrule_kube-prometheus-stack-kubernetes-system-kubelet.yaml
- prometheusrule_kube-prometheus-stack-kubernetes-system-scheduler.yaml
- prometheusrule_kube-prometheus-stack-kubernetes-system.yaml
- prometheusrule_kube-prometheus-stack-node-exporter.rules.yaml
- prometheusrule_kube-prometheus-stack-node-exporter.yaml
- prometheusrule_kube-prometheus-stack-node-network.yaml
- prometheusrule_kube-prometheus-stack-node.rules.yaml
- prometheusrule_kube-prometheus-stack-prometheus-operator.yaml
- prometheusrule_kube-prometheus-stack-prometheus.yaml
- role_kube-prometheus-stack-admission.yaml
- role_kube-prometheus-stack-grafana.yaml
- rolebinding_kube-prometheus-stack-admission.yaml
- rolebinding_kube-prometheus-stack-grafana.yaml
- secret_alertmanager-kube-prometheus-stack-alertmanager.yaml
- secret_kube-prometheus-stack-grafana.yaml
- service_kube-prometheus-stack-alertmanager.yaml
- service_kube-prometheus-stack-coredns.yaml
- service_kube-prometheus-stack-grafana.yaml
- service_kube-prometheus-stack-kube-controller-manager.yaml
- service_kube-prometheus-stack-kube-etcd.yaml
- service_kube-prometheus-stack-kube-proxy.yaml
- service_kube-prometheus-stack-kube-scheduler.yaml
- service_kube-prometheus-stack-kube-state-metrics.yaml
- service_kube-prometheus-stack-operator.yaml
- service_kube-prometheus-stack-prometheus-node-exporter.yaml
- service_kube-prometheus-stack-prometheus.yaml
- serviceaccount_kube-prometheus-stack-admission.yaml
- serviceaccount_kube-prometheus-stack-alertmanager.yaml
- serviceaccount_kube-prometheus-stack-grafana-test.yaml
- serviceaccount_kube-prometheus-stack-grafana.yaml
- serviceaccount_kube-prometheus-stack-kube-state-metrics.yaml
- serviceaccount_kube-prometheus-stack-operator.yaml
- serviceaccount_kube-prometheus-stack-prometheus-node-exporter.yaml
- serviceaccount_kube-prometheus-stack-prometheus.yaml
- servicemonitor_kube-prometheus-stack-alertmanager.yaml
- servicemonitor_kube-prometheus-stack-apiserver.yaml
- servicemonitor_kube-prometheus-stack-coredns.yaml
- servicemonitor_kube-prometheus-stack-grafana.yaml
- servicemonitor_kube-prometheus-stack-kube-controller-manager.yaml
- servicemonitor_kube-prometheus-stack-kube-etcd.yaml
- servicemonitor_kube-prometheus-stack-kube-proxy.yaml
- servicemonitor_kube-prometheus-stack-kube-scheduler.yaml
- servicemonitor_kube-prometheus-stack-kube-state-metrics.yaml
- servicemonitor_kube-prometheus-stack-kubelet.yaml
- servicemonitor_kube-prometheus-stack-operator.yaml
- servicemonitor_kube-prometheus-stack-prometheus-node-exporter.yaml
- servicemonitor_kube-prometheus-stack-prometheus.yaml
- validatingwebhookconfiguration_kube-prometheus-stack-admission.yaml
