apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: fastapi-app
          env:
            - name: ENVIRONMENT
              value: "prod"
