unifiedService:
  type: NodePort
ingress:
  ingressClassName: "tailscale"
  hosts:
    - unifi
  tls:
    - secretName: example-tls
      hosts:
        - unifi
persistence:
  enabled: true
  storageClass: "local-path"