apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-example-nonprod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:pmpaulino/hello-dagger-fastapi-rye.git'
    targetRevision: main
    path: 'k8s/overlays/nonprod'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
