apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-example
  labels:
    app: fastapi-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-example
  template:
    metadata:
      labels:
        app: fastapi-example
    spec:
      containers:
        - name: fastapi-example
          image: nginx:latest
          ports:
            - containerPort: 80
