apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# This can be swapped out to a url once the repo is public.
# Unsure if it should be the homelab-argo-apps or argocd repo.
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.14.2/manifests/install.yaml
- ../homelab-argo-apps/environments/nonprod/
- namespace.yaml

patches:
- target:
    labelSelector: "app.kubernetes.io/part-of=argocd"
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: argocd

secretGenerator:
  # GitHub repo credentials secret
  - name: github-repo-creds
    type: Opaque
    namespace: argocd
    options:
      labels:
        argocd.argoproj.io/secret-type: repo-creds
    files:
      - sshPrivateKey=tmp/sshprivatekey
    literals:
      - type=git
      - url=ssh://git@github.com/

  # Sealed Secrets TLS secret
  - name: sealed-secrets-key
    type: kubernetes.io/tls
    namespace: sealed-secrets
    options:
      labels:
        sealedsecrets.bitnami.com/sealed-secrets-key: active
    files:
      - tmp/tls.crt
      - tmp/tls.key
