apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap_hass-configuration.yaml
- configmap_init-script.yaml
- ingress_home-assistant.yaml
- pod_home-assistant-test-connection.yaml
- service_home-assistant.yaml
- serviceaccount_home-assistant.yaml
- statefulset_home-assistant.yaml
