---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgABwu2jA7PdW3PbvDh3H13i4fMAJxgyQkKbF510lmvkRLY7pjSfBpHT5mV9wo11SPD1zkSWeMGbxXtnpyJP14B93LZ1jx8h99ypFXt/J0460qVENjgkf1wSeVvMLLYo15LZ6n7O7JhLM7ApFKqb/eQdjQ5yfPKmSEvGPHEN2t62vt7aisqH8+Kl5neRkcgntEQmIhp8VP5HCW6P7MLTLtjwSvD2yvcf1riTOlLMkVR5M0QYjbhazF6OEAtpTAx0vTixT0kZ9ff42A5mh/5Td3J9/eT1PyBl1ASH9P1lC8NizsQUSWv47kSTuZdN3MjlgQ+CKfP/OGmLqe08vfwt0CZh9cYIJpsGttkdd898I69oUXJv4pHy2TFaBhxR0akvMU+1XaEEY73UIcJyHlPRxeSG7n3UPyjwW+QB6GTFfEJV/veeAU33MFro+teQ9O9xZPS+YQPamJqyUKNqG3rHNleok4vIAQ172fqGLmh0ePPWoCeil2gLCdSs5f6cd2wLqqfT++wqiyBi58yF7YE/1BrGcI1RMbquGF3u7yYA+KONZQJRkpuBguq5aGiq1l7pkL8c+HNUUuzREDWoOh61zobrUAu5MpDBh2uaC/TX9ZtxN35S8gHrFP6dPYAZPCBfG0McyRcKwvInQzcxu+GwH8fTKhw/IFZzWTlMqHzzPf/B9+S8xT2YTWVC/3PDFm4RN2x0WlJRRNUUmqBL/WUz8y9tJg==
    client_secret: AgCCZU5UvNafVuO131l6IXVXxtzOSvnGJmz/yX2lkL4o4ecaptorb8GruCL9CVMldNmcLnGlMM8gnPHE4TuyL4AY11Nl/+giY9dUSlp0Jl5ASfvXyFuqQ+0jJZT81isXVF+yEPbMncv56NH6r5oXSbO6CZ5FExRHBr2YSHUfVIP+J4YebF745/8pArjhqcGXK/5O2uQ6sWrC40WPK/cUMdwOdER+jZKH9etervsT+0APiyqy6djbb+V5jCjF8ea9dTqQ8VxfDq1eZ2WcNapHqHIXSNk0q5sRv9L1nhKSckNFiJbq7t+vNkznYeVIiZvj3mUnjeKwDYt9y4ir24vyGRa4lM91DTQmTJWS3eg9Zt8AiwYCoOGDM1hoS6yWhQdD84RmvWnT1R+qNIG1BpAyKrz10zrTNMvLXKsHOoH+7PD/pVOAePPDwtW8PeOa9pY45YKMFGVFrWnos4Q+2PxmmRevaMOrSdbh+Akc48MOAFvAqAWRBXMbaa83tVRPSphcwWoSJQsN/rFSa/nNTR/XyQQQUMolisYP1WXWP6a+ZyfJLC+NUutgkkl3E1sVH2pTxVI3DgfE/V9q9JbIq/vbqKyKoK4YUwNhu6kFkzmKQSjsdKgBbdZcDQfIGTbJa+H/y1ODD5qHLQYDJ3mPB3ExpQa019UTfsoom7Hyku6CqHNMiigOYmRxInbK1JH/bj6GhUE+/qbpAZ+zsBWMRWrzc/4PquJhoVS2EKJZXnKcJbsxUP+2bFjkrPadhdxBiB48SbKbyqCNGTyinh0Vlv19QKqi
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
    type: Opaque
