apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml

patches:
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: argocd-server
      namespace: argocd
    spec:
      template:
        spec:
          containers:
          - name: argocd-server
            args:
            - /usr/local/bin/argocd-server
            - --insecure
  target:
    kind: Deployment
    name: argocd-server
