apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml

patches:
- patch: |
    apiVersion: v1
    kind: Namespace
    metadata:
      name: kube-prometheus-stack
      labels:
        pod-security.kubernetes.io/enforce: privileged
  target:
    kind: Namespace
    name: kube-prometheus-stack
