apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
  - target:
        kind: Ingress
        name: unifi
    patch: |-
      - op: remove #action 
        path: /spec/tls/0/secretName
      - op: replace #action 
        path: /spec/rules/0/http/paths/0/backend/service/port/name
        value: https
  - target:
        kind: Deployment
        name: unifi
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/ports/0/name
        value: https
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe/httpGet/port
        value: https
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/httpGet/port
        value: https
      - op: replace
        path: /spec/template/spec/containers/0/startupProbe/httpGet/port
        value: https
  - target:
      kind: Service
      name: unifi-gui
    patch: |-
      - op: replace
        path: /spec/ports/0/name
        value: https
      - op: replace
        path: /spec/ports/0/targetPort
        value: https