apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-config
  namespace: home-assistant
data:
  configuration.yaml: |
    # Loads default set of integrations. Do not remove.
    default_config:

    # Load frontend themes from the themes folder
    frontend:
      themes: !include_dir_merge_named themes

    # HTTP configuration for reverse proxy
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.244.0.0/16
        - 10.96.0.0/12
        - 172.16.0.0/12
        - 192.168.0.0/16
        - 100.64.0.0/10

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml
  automations.yaml: ""
  scripts.yaml: ""
  scenes.yaml: "" 