apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../helm
- configmap.yaml
- ingress.yaml

patches:
  - target:
        kind: StatefulSet
        name: home-assistant
    patch: |-
      # Add the config volume
      - op: add
        path: /spec/template/spec/volumes/1
        value:
          name: home-assistant-config
          configMap:
            name: home-assistant-config
      # Add the config volume mounts
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/1
        value:
          name: home-assistant-config
          mountPath: /config/configuration.yaml
          subPath: configuration.yaml
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/2
        value:
          name: home-assistant-config
          mountPath: /config/automations.yaml
          subPath: automations.yaml
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/3
        value:
          name: home-assistant-config
          mountPath: /config/scripts.yaml
          subPath: scripts.yaml
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/4
        value:
          name: home-assistant-config
          mountPath: /config/scenes.yaml
          subPath: scenes.yaml
