---
# Source: tailscale-operator/templates/proxy-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: proxies
  namespace: tailscale
subjects:
  - kind: ServiceAccount
    name: proxies
    namespace: tailscale
roleRef:
  kind: Role
  name: proxies
  apiGroup: rbac.authorization.k8s.io
# Source: tailscale-operator/templates/deployment.yaml
# Copyright (c) Tailscale Inc & AUTHORS
# SPDX-License-Identifier: BSD-3-Clause
