---
# Source: kube-prometheus-stack/templates/prometheus-operator/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kube-prometheus-stack-operator
  namespace: kube-prometheus-stack
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/version: 69.2.0
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-69.2.0
    release: kube-prometheus-stack
    heritage: Helm
    app: kube-prometheus-stack-operator
    app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
    app.kubernetes.io/component: prometheus-operator
spec:
  ports:
    - name: https
      port: 443
      targetPort: https
  selector:
    app: kube-prometheus-stack-operator
    release: kube-prometheus-stack
  type: ClusterIP
