apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: unifi
          image: your-docker-registry/unifi:nonprod
          env:
            - name: ENV
              value: "nonprod"
