apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: unifi
          image: your-docker-registry/unifi:prod
          env:
            - name: ENV
              value: "prod"
