apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unifi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:pmpaulino/homelab.git'
    targetRevision: main
    path: 'apps/unifi/base'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: unifi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true